# Generated by Django 5.2.3 on 2025-06-25 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)', verbose_name='Día de la semana')),
                ('start_time', models.TimeField(help_text='Hora de apertura de esta franja horaria')),
                ('end_time', models.TimeField(help_text='Hora de cierre de esta franja horaria')),
                ('hairdresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='core.hairdresser')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='valid_working_hours_range')],
            },
        ),
    ]
