# Generated by Django 5.2.3 on 2025-06-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
    ]
