# Generated by Django 5.2.3 on 2025-07-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hairdresser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='La imagen que se mostrará como principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.hairdresserimage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
    ]
