# Generated by Django 5.2.3 on 2025-07-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hairdresser_cover_image_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'No se presentó')], default='PENDING', max_length=10),
        ),
    ]
