# Generated by Django 5.2.3 on 2026-06-16 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_amount_to_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='El precio del servicio en el momento de la reserva', max_digits=8),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='La imagen que se mostrará como principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.hairdresserimage'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(verbose_name='Endpoint')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256dh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
