# Generated by Django 5.2.3 on 2026-06-29 04:35

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID de pago')),
                ('mp_request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de request de MercadoPago')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado con éxito')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Monto pagado'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Para turnos PENDING con pago digital pendiente: fecha/hora límite para completar el pago antes de que se libere el slot.', null=True, verbose_name='Expira en'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, help_text='ID del pago en MercadoPago para procesar reembolsos', max_length=100, null=True, verbose_name='ID de pago de MercadoPago'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Pago en el local / Saldo en el local'), ('FULL', 'Pago completo adelantado')], default='CASH', max_length=10, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='default_allow_on_site_payment',
            field=models.BooleanField(default=True, verbose_name='Permitir pago en el local por defecto'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='default_allow_prepayment',
            field=models.BooleanField(default=True, verbose_name='Permitir pago adelantado (100% online) por defecto'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='default_deposit_type',
            field=models.CharField(choices=[('FIXED', 'Monto fijo'), ('PERCENTAGE', 'Porcentaje')], default='FIXED', max_length=10, verbose_name='Tipo de seña por defecto'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='default_deposit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor de seña por defecto'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='mercadopago_access_token',
            field=core.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Token de acceso de MercadoPago'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='mercadopago_active',
            field=models.BooleanField(default=False, verbose_name='Habilitar cobros digitales'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='mercadopago_refresh_token',
            field=core.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Token de refresco de MercadoPago'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='mercadopago_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración del token de MercadoPago'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='mercadopago_user_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID de usuario de MercadoPago'),
        ),
        migrations.AddField(
            model_name='hairdresser',
            name='requires_deposit',
            field=models.BooleanField(default=False, verbose_name='Requerir seña obligatoria al reservar'),
        ),
        migrations.AddField(
            model_name='service',
            name='allow_on_site_payment',
            field=models.BooleanField(default=True, verbose_name='Permitir pago en el local'),
        ),
        migrations.AddField(
            model_name='service',
            name='allow_prepayment',
            field=models.BooleanField(default=True, verbose_name='Permitir pago adelantado (100% online)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deposit_type',
            field=models.CharField(choices=[('FIXED', 'Monto fijo'), ('PERCENTAGE', 'Porcentaje')], default='FIXED', max_length=10, verbose_name='Tipo de seña específico'),
        ),
        migrations.AddField(
            model_name='service',
            name='deposit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor de seña específico'),
        ),
        migrations.AddField(
            model_name='service',
            name='override_deposit',
            field=models.BooleanField(default=False, verbose_name='Sobrescribir configuración de seña'),
        ),
        migrations.AddField(
            model_name='service',
            name='override_payment_modes',
            field=models.BooleanField(default=False, verbose_name='Sobrescribir formas de pago'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID de pago de MercadoPago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto transaccionado')),
                ('status', models.CharField(max_length=50, verbose_name='Estado del pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.appointment', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
            },
        ),
        migrations.CreateModel(
            name='PendingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='ID de pago de MercadoPago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a reembolsar')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos de reembolso')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Último error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_refund', to='core.appointment', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Reembolso pendiente',
                'verbose_name_plural': 'Reembolsos pendientes',
            },
        ),
    ]
