# Generated by Django 5.2.3 on 2026-06-30 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='extra_minutes',
            field=models.IntegerField(default=0, help_text='Minutos añadidos (+) o reducidos (-) al servicio original.', verbose_name='Minutos adicionales'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_notified_start_time',
            field=models.DateTimeField(blank=True, help_text='Registra el último horario de inicio que fue notificado al cliente para evitar spam de reprogramaciones.', null=True, verbose_name='Último horario notificado'),
        ),
        migrations.CreateModel(
            name='EarlyStartOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('minutes_available', models.PositiveIntegerField(help_text='Minutos que se pueden adelantar')),
                ('new_start_time', models.DateTimeField(help_text='El nuevo start_time propuesto')),
                ('expires_at', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_start_offers', to='core.appointment', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Oferta de adelanto',
                'verbose_name_plural': 'Ofertas de adelanto',
            },
        ),
    ]
