# Generated by Django 5.2.3 on 2026-07-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appointment_extra_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(blank=True, help_text='Nombre del cliente para reservas presenciales (walk-ins).', max_length=150, null=True, verbose_name='Nombre del cliente presencial'),
        ),
    ]
