# Generated by Django 5.2.3 on 2026-07-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appointment_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='slot_duration',
            field=models.PositiveIntegerField(choices=[(10, '10 minutos'), (15, '15 minutos'), (20, '20 minutos'), (30, '30 minutos'), (60, '60 minutos')], default=15, help_text='Define la grilla de tiempo del calendario y los múltiplos para duraciones de servicios y turnos.', verbose_name='Duración del slot (agenda)'),
        ),
    ]
