# Generated by Django 5.2.3 on 2026-07-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hairdresser_slot_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hairdresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='core.hairdresser')),
            ],
            options={
                'verbose_name': 'Pausa',
                'verbose_name_plural': 'Pausas',
                'ordering': ['start_time'],
            },
        ),
    ]
