"""
Django settings for stilo project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "core",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "stilo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.vapid_keys",
            ],
        },
    },
]

WSGI_APPLICATION = "stilo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

default_db_url = "sqlite:///" + str(BASE_DIR / "db.sqlite3")
DATABASES = {"default": dj_database_url.parse(config("DATABASE_URL", default=default_db_url))}  # type: ignore


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Salta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Extra settings

AUTH_USER_MODEL = "core.User"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
STATIC_ROOT = BASE_DIR / "staticfiles"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}


# Configuración del Correo (Brevo API)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="Stilo <no-reply@stilo.com>")
BREVO_API_KEY = config("BREVO_API_KEY", default="")

if DEBUG and not BREVO_API_KEY:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "core.email_backend.BrevoEmailBackend"

# Secreto de seguridad para tareas programadas (cron)
CRON_SECRET = config("CRON_SECRET", default="desarrollo_secreto")

# Web Push VAPID keys
VAPID_PUBLIC_KEY = config("VAPID_PUBLIC_KEY", default="")
VAPID_PRIVATE_KEY = config("VAPID_PRIVATE_KEY", default="")
# Integración MercadoPago OAuth
MERCADOPAGO_CLIENT_ID = config("MERCADOPAGO_CLIENT_ID", default="")
MERCADOPAGO_CLIENT_SECRET = config("MERCADOPAGO_CLIENT_SECRET", default="")
# Clave para cifrado de campos sensibles en base de datos
FIELD_ENCRYPTION_KEY = config("FIELD_ENCRYPTION_KEY", default="")
# Token de prueba del panel de desarrollador (sandbox, sin modo marketplace)
MERCADOPAGO_TEST_ACCESS_TOKEN = config("MERCADOPAGO_TEST_ACCESS_TOKEN", default="")
# Secreto del webhook para validación de firma de MercadoPago
MERCADOPAGO_WEBHOOK_SECRET = config("MERCADOPAGO_WEBHOOK_SECRET", default="")
# Comisión del marketplace por transacciones en MercadoPago (porcentaje)
MERCADOPAGO_COMMISSION_PERCENTAGE = config(
    "MERCADOPAGO_COMMISSION_PERCENTAGE", default="2.0"
)
# Modo sandbox de MercadoPago (independiente del DEBUG del sitio)
# True  → usa sandbox_init_point y el token de prueba (MERCADOPAGO_TEST_ACCESS_TOKEN)
# False → usa init_point y el token OAuth real del peluquero
MERCADOPAGO_SANDBOX = config("MERCADOPAGO_SANDBOX", default=DEBUG, cast=bool)

# Orígenes confiables para CSRF (requerido al acceder mediante túneles HTTPS en desarrollo local)
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if host and not host.startswith((".", "localhost", "127.0.0.1", "[::1]"))
]
CSRF_TRUSTED_ORIGINS += ["http://localhost", "http://127.0.0.1"]

# Confiar en el encabezado de proxy SSL provisto por el túnel (para generar enlaces HTTPS)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Validación obligatoria de secretos en producción
if not DEBUG:
    assert MERCADOPAGO_WEBHOOK_SECRET, "¡Se requiere MERCADOPAGO_WEBHOOK_SECRET en producción!"


# Configuración de Logging temático: archivos separados por funcionalidad
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'mp_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'mercadopago.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 3,
        },
        'cron_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'cron.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
        },
        'core_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'core.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
        },
    },
    'loggers': {
        'mp': {
            'handlers': ['console', 'mp_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'cron': {
            'handlers': ['console', 'cron_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'core_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['core_file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


